name: Docusaurus

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/docusaurus.yml
      - docusaurus/**
      - drinks/**
      - "!**.gitignore"

  workflow_dispatch:

defaults:
  run:
    working-directory: docusaurus

env:
  path: docusaurus

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        # with:
        # node-version: latest # Implicit?
        # cache: npm # TEST!

      - name: CHECK VERSION # TMP
        run: node --version

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Upload artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.path }}/build

  release:
    name: Release
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest

    # permissions:
    #   pages: write
    #   id-token: write

    environment:
      # name: github-pages
      name: prod
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Deploy app
        id: deploy
        uses: actions/deploy-pages@v4
