name: Drink stats

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/stats.yml
      - scripts/stats.py
      - drinks/**

  workflow_dispatch:

defaults:
  run:
    working-directory: scripts

jobs:
  validate:
    name: Drink stats
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Drink stats
        run: ./stats.py
